[package]
name = "rosu-memory-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "rosu_memory_python"
crate-type = ["cdylib"]

[dependencies]
rosu-memory-lib = "1.0.3"
rosu-mem = "2.0.0"
pyo3 = { version = "0.25", features = ["extension-module"] } 
